### ISSUE TITLE
Polyphonic music extension 

### ISSUE THREAD

**Issue by peiherng97** [RichardYang40148/mgeval#1]
Hi I was wondering is this toolbox update with polyphonic music extension?

**Comment by RichardYang40148** [comment]
Hi, this toolbox is designed for monophonic melody, and we haven't scheduled any update for polyphonic music extensions so far.
However, there are several measures can also be applied on polyphonic cases such as:
1. Pitch count
2. Pitch class histogram
3. Pitch class transition matrix
4. Pitch range
5. Note count
