### ISSUE TITLE
Python-midi cannot be installed

### ISSUE THREAD

**Issue by huangqing6** [RichardYang40148/mgeval#3]
Python-midi cannot be installed in pycharm. The program shows a question(ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.). I need your help very much, thanks!

**Comment by RichardYang40148** [comment]
Please refer to the python-midi repo for related issues.
https://github.com/vishnubob/python-midi/issues
Installation issues are likely environment dependent, there're a few similar issues up there and hope you can find a solution for your case
